### ISSUE TITLE
custom work

### ISSUE THREAD

**Issue by dnikola** [shaikhsajid1111/social-media-profile-scrapers#3]
Hello,

we would like to use your repo and code for some custom work.
Are you available for extra work? I am not sure if this is right way to contact you but could not find any other contact (on twitter you are not available for messaging)

Regards!

**Comment by shaikhsajid1111** [comment]
Yes,sure you can

**Comment by dnikola** [comment]
Great, thanks for fast replay!
Can you tell me is this available to scrape post from 
facebook pages
facebook profiles
instagram profiles
twitter profiles

**Comment by shaikhsajid1111** [comment]
It can scrap all mentioned profiles. Can't say about Facebook pages though

**Comment by dnikola** [comment]
can you give me some contact? Slack or skype or etc.

Thanks

**Comment by shaikhsajid1111** [comment]
I'm not available on those, do you use instagram?, My account name is @shaikhsajid1111
