### ISSUE TITLE
Error when running the script: 'str' object has no attribute 'get'

### ISSUE THREAD

**Issue by tina1998612** [shaikhsajid1111/social-media-profile-scrapers#4]
As the title suggests, please let me know how to resolve this. Thanks!

**Comment by shaikhsajid1111** [comment]
Hi!, I think you have not set the driver's settings, can you please check `settings.py` file with dictionary named as 'DRIVER_SETTINGS'. You have to edit those dictionaries keys i.e `PATH` is the path of the driver and `BROWSER_NAME` is the name of the browser that driver support. I hope this will resolve the issue :slightly_smiling_face:
