### ISSUE TITLE
Setting up webdriver manager is a hectic process

### ISSUE THREAD

**Issue by RohanDas28** [shaikhsajid1111/social-media-profile-scrapers#5]
Hey setting up the webdriver manager is a very hectic process, You have to download the webdriver file, then place it somewhere safe and then also link it to the code. Why do all of that when we have a python module for that? You can use (pip install webdriver_manager and then just read the documentation ) to skip all the above steps. It is not only reliable its easier to use too. 😊

**Comment by shaikhsajid1111** [comment]
Hi! @RohanDas28 thank you for your suggestion. I agree with you, I'm thinking to implement your idea :smile:

**Comment by RohanDas28** [comment]
Yes Brother You can close this issue now 😉
