### ISSUE TITLE
Invalid Syntax

### ISSUE THREAD

**Issue by Sarnes** [shaikhsajid1111/social-media-profile-scrapers#6]
Hello, new to programming so please bare with me
I don't understand what is wrong here, but i have downloaded the code and installed the requirements but whenever i run any code from it, it states invalid syntax and this error.

  File "instagram.py", line 30
    browser_option.add_argument(f'user-agent={ua}')
                                                 ^
SyntaxError: invalid syntax

Whenever I enter this, python instagram.py _username_

**Comment by shaikhsajid1111** [comment]
Hi!, Can you tell me what version of Python you're using and if you made any changes to script?
